from __future__ import annotations

import importlib.util
import sys
import tempfile
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]


def load_module(name: str, path: Path):
    spec = importlib.util.spec_from_file_location(name, path)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


generator = load_module(
    "papertrace_host_wrapper_generator",
    ROOT / ".agent/scripts/generate_agent_skill_wrappers.py",
)
validator = load_module(
    "papertrace_host_wrapper_validator",
    ROOT / ".agent/scripts/validate_agent_skill_wrappers.py",
)


def skill_text(name: str, description: str) -> str:
    return f"""---
name: {name}
description: {description}
---

# {name}

## Purpose
Test fixture.

## Workflow
1. Do one bounded test action.

## Output Contract
- one result

## Boundaries
- no external work
"""


class HostSkillExposureTests(unittest.TestCase):
    def _make_repo(self, root: Path) -> None:
        skills = root / ".agent" / "skills"
        for name, description in {
            "00-router": "Front door that routes one product action and executes one internal module.",
            "01-project-brief": "Internal project-state module that is not a host entrypoint.",
            "grill-me": "Explicit read-only decision interview that asks one question at a time.",
        }.items():
            directory = skills / name
            directory.mkdir(parents=True, exist_ok=True)
            (directory / "SKILL.md").write_text(
                skill_text(name, description), encoding="utf-8"
            )

        override = skills / "grill-me" / "wrappers"
        override.mkdir()
        (override / "claude.yaml").write_text(
            "disable-model-invocation: true\nargument-hint: '[plan]'\n",
            encoding="utf-8",
        )

    def test_generator_exposes_only_router_and_explicit_grill(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            self._make_repo(root)
            self.assertEqual(
                0,
                generator.main(
                    ["--repo-root", str(root), "--target", "both", "--clean"]
                ),
            )
            for host in (".claude", ".codex"):
                names = {
                    path.parent.name
                    for path in (root / host / "skills").glob("*/SKILL.md")
                }
                self.assertEqual({"00-router", "grill-me"}, names)
            self.assertEqual(
                0,
                validator.main(
                    [
                        "--canonical",
                        str(root / ".agent" / "skills"),
                        "--claude",
                        str(root / ".claude" / "skills"),
                        "--codex",
                        str(root / ".codex" / "skills"),
                    ]
                ),
            )

    def test_validator_rejects_internal_skill_wrapper(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            self._make_repo(root)
            generator.main(["--repo-root", str(root), "--target", "both", "--clean"])
            extra = root / ".claude" / "skills" / "01-project-brief"
            extra.mkdir(parents=True)
            (extra / "SKILL.md").write_text(
                """---
name: 01-project-brief
description: Internal module incorrectly exposed as a host entrypoint.
---

<!-- Generated by .agent/scripts/sync_agent_skill_wrappers.sh. Do not edit manually. -->

@../../../.agent/skills/01-project-brief/SKILL.md
""",
                encoding="utf-8",
            )
            self.assertEqual(
                1,
                validator.main(
                    [
                        "--canonical",
                        str(root / ".agent" / "skills"),
                        "--claude",
                        str(root / ".claude" / "skills"),
                        "--codex",
                        str(root / ".codex" / "skills"),
                    ]
                ),
            )

    def test_control_plane_contract_is_content_first(self) -> None:
        router = (ROOT / ".agent/skills/00-router/SKILL.md").read_text(
            encoding="utf-8"
        )
        safety = (ROOT / ".agent/skills/14-agent-safety/SKILL.md").read_text(
            encoding="utf-8"
        )

        for token in (
            "Turn a broad request into one substantive product change",
            "Modify the requested product in the same turn",
            "Validate once with the closest direct check",
            "Audit skills require explicit audit intent",
            "Do not calculate hashes or create receipts",
        ):
            self.assertIn(token, router)

        for token in (
            "routine local read",
            "paid API, cloud GPU, or remote compute budget",
            "Do not build action fingerprints",
            "Return immediately to the original product task",
        ):
            self.assertIn(token, safety)


if __name__ == "__main__":
    unittest.main()
